services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/geo/Desktop/sonarr/config:/config
      - /home/geo/Desktop/sonarr/tv:/tv #optional
      - /home/geo/Desktop/sonarr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /home/geo/Desktop/sonarr/radarr/data:/config
      - /home/geo/Desktop/sonarr/movies:/movies #optional
      - /home/geo/Desktop/sonarr/qbittorrent/downloads:/downloads #optional

    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/geo/Desktop/sonarr/jackett/data:/config
      - /home/geo/Desktop/sonarr/qbittorrent/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/geo/Desktop/sonarr/qbittorrent/appdata:/config
      - /home/geo/Desktop/sonarr/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/geo/Desktop/sonarr/jellyfin/library:/config
      - /home/geo/Desktop/sonarr/tv:/data/tvshows
      - /home/geo/Desktop/sonarr/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
